version: "3.5"
# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
    guacnetwork_compose:
        driver: bridge

services:
    # guacd
    guacd:
        image: guacamole/guacd
        networks:
            guacnetwork_compose:
        restart: always
        volumes:
            - ./drive:/drive:rw
            - ./record:/record:rw
    #MySql
    mysql:
        image: mysql:8.0
        networks:
            guacnetwork_compose:
        restart: on-failure
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: redge_guac
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: redge
            MYSQL_PASSWORD: r3dg3_houston2021
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./mysql-data:/var/lib/mysql/
    #guacamole
    guacamole:
        image: "guacamole/guacamole"
        links:
            - guacd
        depends_on:
            - guacd
            - mysql
        networks:
            guacnetwork_compose:
        ports:
            - "8080:8080"
        environment:
            - GUACD_HOSTNAME=guacd
            - GUACD_PORT=4822
            - MYSQL_HOSTNAME=mysql
            - MYSQL_DATABASE=redge_guac
            - MYSQL_USER=redge
            - MYSQL_PASSWORD=r3dg3_houston2021
#Volumes
# volumes:
#     mysql-data:
#     postgres-data:
